FROM docker:rc-dind-rootless

FROM gcr.io/projectsigstore/cosign:v0.3.1

COPY --from=0 /usr/local/bin/docker-credential-gcr /usr/bin/docker-credential-gcr
COPY --from=0 /go/src/github.com/awslabs/amazon-ecr-credential-helper/bin/local/docker-credential-ecr-login /usr/bin/docker-credential-ecr-login
COPY --from=0 /go/src/github.com/chrismellard/docker-credential-acr-env/build/docker-credential-acr-env /usr/bin/docker-credential-acr
