pipeline {
  agent {
    kubernetes {
      label 'default maven build-pod'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }

  environment {
    DOCKER_HUB=credentials('dockerhub-cred')
    IMAGE_NAME='opeomotayo/java-image'
    IMAGE_VERSION='latest'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }

  stages {
    stage('Delete Image If Exists') {
      steps {
          sh 'docker rmi $IMAGE_NAME:$IMAGE_VERSION || (echo "Image $IMAGE_NAME:$IMAGE_VERSION does not exist so not removed."; exit 0)'
          sh 'docker system prune -a --volumes --force'
      }
    }
    stage('Create Container Image') {
      steps {
        dir('container-image-security/syft-generate-sbom'){
          sh 'docker build --tag $IMAGE_NAME:$IMAGE_VERSION .'
          sh 'docker image ls'
        }
      }
    }
    stage('Publish Image') {
      steps {
        sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
        sh 'docker push $IMAGE_NAME:$IMAGE_VERSION'
      }
    }
    stage('Generate SBOM') {
      steps {
        dir('container-image-security/syft-generate-sbom'){
          container('security-tools'){
            sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
            // sh 'syft packages $IMAGE_NAME:$IMAGE_VERSION --scope AllLayers'
            sh 'syft packages $IMAGE_NAME:$IMAGE_VERSION --scope AllLayers -o spdx > ./java-image-sbom.spdx' //json, syclonedx or -vv
            sh 'cat ./java-image-sbom.spdx'
          }
        }
      }
    }
    // stage('Does WireFrame Exist?') {
    //   steps {
    //     dir('container-image-security/syft-generate-sbom'){
    //       container('security-tools'){
    //         script {
    //           def WireFrameFound = sh(returnStatus:true,script:'''
    //               cat ./java-image-sbom.spdx | jq -e '.artifacts[] | select(.name =="WireFrame")'
    //             ''')
    //           if(WireFrameFound == 0) {
    //             error(message:"WireFrame was found in the SBOM. It should not be there.")
    //           }
    //         }
    //       }
    //     }
    //   }
    // }
    stage('Finally done') {
      steps {
        echo 'if I made it here, no WireFrame was found'
      }
    }

  }
}