pipeline {
  agent {
    kubernetes {
      label 'default maven build-pod'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }

  environment {
    DOCKER_HUB=credentials('dockerhub-cred')
    IMAGE_NAME='opeomotayo/java-image'
    IMAGE_VERSION='latest'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }

  stages {
    stage('Delete Image If Exists') {
      steps {
        dir('container-image-security/cosign-sign-image'){
          sh 'docker rmi $IMAGE_NAME:$IMAGE_VERSION || (echo "Image $IMAGE_NAME:$IMAGE_VERSION does not exist so not removed."; exit 0)'
          sh 'docker system prune -a --volumes --force'
        }
      }
    }
    stage('Create container image') {
      steps {
        dir('container-image-security/syft-generate-sbom'){
          sh 'docker build --tag $IMAGE_NAME:$IMAGE_VERSION .'
          sh 'docker image ls'
        }
      }
    }
    stage('push image') {
      steps {
        sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
        sh 'docker push $IMAGE_NAME:$IMAGE_VERSION'
      }
    }
    stage('Generate SBOM') {
      steps {
        dir('container-image-security/syft-generate-sbom'){
          container('security-tools'){
            sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
            // sh 'syft packages $IMAGE_NAME:$IMAGE_VERSION --scope AllLayers'
            syft packages $IMAGE_NAME:$IMAGE_VERSION --scope AllLayers -o json > ./java-image-sbom.json
            cat ./java-image-sbom.json
          }
        }
      }
    }
    stage('Does WireFrame exist?') {
      steps {
        dir('container-image-security/syft-generate-sbom'){
          container('security-tools'){
            script {
              def WireFrameFound = sh(returnStatus:true,script:'''
                  cat ./java-image-sbom.json | jq -e '.artifacts[] | select(.name =="WireFrame")'
                ''')
              if(WireFrameFound == 0) {
                error(message:"WireFrame was found in the SBOM. It should not be there.")
              }
            }
          }
        }
      }
    }
    stage('Finally done') {
      steps {
        echo 'if I made it here, no WireFrame was found'
      }
    }

  }
}