pipeline {

  environment {
    IMAGE_TAG = "${env.BUILD_NUMBER}"
  }

  options {
      buildDiscarder(logRotator(numToKeepStr: '3'))
   }

  agent {
    kubernetes {
      label 'update-manifest'
      defaultContainer 'jnlp'
      yamlFile 'build-pod.yaml'
    }
  }

  stages {
    stage('Update GIT') {
      steps{
        script {
          dir("flask-manifest"){
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
              withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                sh "git config user.email manifest_updater_bot@gmail.com"
                sh "git config user.name manifest_updater_bot"
                //sh "git switch master"
                sh "cat flask-deployment.yaml"
                sh "sed -i 's+opeomotayo/flask-image.*+opeomotayo/flask-image:${DOCKERTAG}+g' flask-deployment.yaml"
                sh "cat flask-deployment.yaml"
                sh "git add ."
                sh "git commit -m 'Done by Jenkins Job: changing manifest image tag to ${IMAGE_TAG}'"
                sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/playground-dependency.git HEAD:master"
              }
            }
          }
        }
      }
    } 
  }
}
