pipeline {

  environment {
    APP_NAME = "flask-image"
    REPO_NAME = "opeomotayo"
    IMAGE_TAG = "${env.BUILD_NUMBER}"
    DOCKER_CRED = "dockerhub"
  }

  options {
      buildDiscarder(logRotator(numToKeepStr: '5'))
   }

  agent {
    kubernetes {
      label 'ci'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }

  stages {
    stage('Update GIT') {
      script {
        dir("flask-manifest"){
          catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
            withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
              //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
              sh "git config user.email opeomotayo@gmail.com"
              sh "git config user.name opeomotayo"
              //sh "git switch master"
              sh "cat deployment.yaml"
              sh "sed -i 's+opeomotayo/flask-image.*+opeomotayo/flask-image:${DOCKERTAG}+g' deployment.yaml"
              sh "cat deployment.yaml"
              sh "git add ."
              sh "git commit -m 'Done by Jenkins Job: changing manifest image tag to ${env.BUILD_NUMBER}'"
              sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/playground-dependency.git HEAD:master"
            }
          }
        }
      }
    } 
  }
}
