pipeline {
  
  agent {
    kubernetes {
      label 'default docker build-pod'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }

  environment {
    DOCKER_HUB=credentials('dockerhub-cred')
    IMAGE_NAME='opeomotayo/java-image'
    IMAGE_VERSION='latest'
    COSIGN_PASSWORD=credentials('cosign-password')
    COSIGN_PRIVATE_KEY=credentials('cosign-private-key')
    COSIGN_PUBLIC_KEY=credentials('cosign-public-key')
  }
  
  stages {
    stage('Delete Image If Exists') {
      steps {
        dir('container-image-security/cosign-sign-image'){
          sh 'docker rmi $IMAGE_NAME:$IMAGE_VERSION || (echo "Image $IMAGE_NAME:$IMAGE_VERSION does not exist so not removed."; exit 0)'
          sh 'docker system prune -a --volumes --force'
        }
      }
    }
    stage('Create Container Image') {
      steps {
        dir('container-image-security/cosign-sign-image'){
          sh 'docker build --tag $IMAGE_NAME:$IMAGE_VERSION .'
          sh 'docker image ls'
        }
      }
    }
    stage('Run Vulnerability Scan') {
      steps {
          container('security-tools'){
            sh 'grype $IMAGE_NAME:$IMAGE_VERSION --scope AllLayers' //--fail-on=critical
          }
      }
    }
    stage('Publish Image') {
      steps {
        sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
        sh 'docker push $IMAGE_NAME:$IMAGE_VERSION'
      }
    }
    stage('Sign Container Image') {
      steps {
        container('security-tools'){
          sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
          sh 'cosign version'
          sh 'cosign sign --key $COSIGN_PRIVATE_KEY $IMAGE_NAME:$IMAGE_VERSION'
        }
      }
    }
    stage('Verify Signed Container Image') {
      steps {
        container('security-tools'){
          sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
          // sh 'cosign version'
          sh 'cosign verify --key $COSIGN_PUBLIC_KEY $IMAGE_NAME:$IMAGE_VERSION'
        }
      }
    }
    stage('Verify Attestation Container Image') {
      steps {
        container('security-tools'){
          sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
          // sh 'cosign version'
          sh 'cosign verify-attestation --key $COSIGN_PUBLIC_KEY $IMAGE_NAME:$IMAGE_VERSION'
        }
      }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}