pipeline {
  agent {
    kubernetes {
      label 'default docker build-pod'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }

  environment {
    AQUA_ROOT_DIR="$WORKSPACE/.aqua"
    PATH="$WORKSPACE/.aqua/bin:$PATH"
  }
  stages {
    stage('Verify aqua installation') {
      steps {
        sh '/usr/local/bin/aqua version'
        sh '/usr/local/bin/aqua --help'
      }
    }
    stage('Install aqua packages') {
      steps {
        sh '/usr/local/bin/aqua i'
      }
    }
    stage('Verify aqua packages') {
      steps {
        sh 'command -v jq'
        sh 'jq --version'
      }
    }
  }
}
