pipeline {
  agent {
    kubernetes {
      label 'default docker build-pod'
      defaultContainer 'aqua'
      yamlFile 'build-pod.yaml'
    }
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }

  // environment {
  //   AQUA_ROOT_DIR="$WORKSPACE/.aqua"
  //   PATH="$WORKSPACE/.aqua/bin:$PATH"
  // }
  stages {
    stage('Verify aqua installation') {
      steps {
        sh 'aqua version'
        sh 'aqua --help'
      }
    }
    stage('Install aqua packages') {
      steps {
        sh 'aqua i'
      }
    }
    stage('Verify aqua packages') {
      steps {
        sh 'command -v jq'
        sh 'jq --version'
      }
    }
  }
}
