pipeline {

  environment {
    APP_NAME = flask-image
    IMAGE_TAG = "${env.BUILD_NUMBER}"
  }

  agent {
    kubernetes {
      label 'ci'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }
  stages {
    stage('Build Image') {
      steps {
        script {
            sh "docker build -t ${IMAGE_TAG} -t opeomotayo/${APP_NAME}:latest ."
        }
      }
    }
    stage('Test') {
      steps {
        app.inside {
            sh 'echo "Tests passed"'
        }  
      }
    }
    // stage('Push Image') {
    //   steps {
    //         docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
    //         app.push("${env.BUILD_NUMBER}")
    //     }
    //   }
    // }
    // stage('Trigger Manifest Update') {
    //   steps {
    //         stage('Trigger Manifest Update') {
    //         echo "triggering updatemanifestjob"
    //         build job: 'updatemanifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
    //     }
    //   }
    // }
  }
}
