pipeline {

  environment {
    APP_NAME = "flask-image"
    REPO_NAME = "opeomotayo"
    IMAGE_TAG = "${env.BUILD_NUMBER}"
  }

  agent {
    kubernetes {
      label 'ci'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }
  stages {
    stage('Build Image') {
      steps {
        script {
            sh "docker build -t ${REPO_NAME}/${APP_NAME}:${IMAGE_TAG} -t ${REPO_NAME}/${APP_NAME}:latest ./flask-code"
        }
      }
    }
    stage('Test') {
      steps {
        script {
            sh 'echo "Tests passed"'
        }  
      }
    }
    stage('Push Image') {
      steps {
            script {
                docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                sh "docker push ${REPO_NAME}/${APP_NAME}:${IMAGE_TAG}"
            }
        }
      }
    }
    // stage('Trigger Manifest Update') {
    //   steps {
    //         stage('Trigger Manifest Update') {
    //         echo "triggering updatemanifestjob"
    //         build job: 'updatemanifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
    //     }
    //   }
    // }
  }
}
