pipeline {
  agent {
    kubernetes {
      label 'default maven build-pod'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }

  environment {
    DOCKER_HUB=credentials('dockerhub-cred')
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }

  stages {
    stage('Delete Image If Exists') {
      steps {
        dir('container-image-security/image-promotion-cd'){
          sh 'echo Delete image if exists'
          // sh 'docker rmi java-docker:latest || (echo "Image java-docker:latest didnt exist so not removed."; exit 0)'
        }
      }
    }
    stage('Update Image Tag') {
      steps {
        dir('container-image-security/image-promotion-cd'){
          sh 'echo Update image tag'
          // sh 'docker build --tag opeomotayo/java-docker:latest .'
          // sh 'docker image ls'
        }
      }
    }
    stage('Publish Image To Nexus') {
      steps {
        dir('container-image-security/image-promotion-cd'){
          sh 'echo Publish image to nexus'
        }
      }
    }
    stage('Verify Image SBOM') {
      steps {
        dir('container-image-security/image-promotion-cd'){
          sh 'echo Verify image SBOM'
        }
      }
    }
    stage('Deploy Container To Prod') {
      steps {
        dir('container-image-security/image-promotion-cd'){
          sh 'echo Deploy container to Prod'
        }
      }
    }
  }
}