pipeline {
  agent {
    kubernetes {
      label 'default maven build-pod'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }

  environment {
    DOCKER_HUB=credentials('dockerhub-cred')
    IMAGE_NAME='opeomotayo/java-image'
    IMAGE_VERSION='latest'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }

  stages {
    stage('Delete Image If Exists') {
      steps {
          sh 'docker rmi $IMAGE_NAME:$IMAGE_VERSION || (echo "Image $IMAGE_NAME:$IMAGE_VERSION does not exist so not removed."; exit 0)'
          sh 'docker system prune -a --volumes --force'
      }
    }
    stage('Create Container Image') {
      steps {
        dir('container-image-security/trivy-scan-image'){
          sh 'docker build --tag $IMAGE_NAME:$IMAGE_VERSION .'
          sh 'docker image ls'
        }
      }
    }
    // stage('Publish Container Image') {
    //   steps {
    //     sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
    //     sh 'docker push $IMAGE_NAME:$IMAGE_VERSION'
    //   }
    // }
    stage('Scan Image Vulnerabilities') {
      steps {
        dir('container-image-security/trivy-scan-image'){
          container('security-tools'){
            sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
            sh 'trivy image --format spdx --output java-image-sbom.spdx $IMAGE_NAME:$IMAGE_VERSION' // cyclonedx, json
            sh 'trivy sbom ava-image-sbom.spdx'
            // sh 'cat java-image-sbom.spdx'
            sh 'trivy image --no-progress --exit-code 0 --security-checks vuln --skip-update --severity HIGH,CRITICAL $IMAGE_NAME:$IMAGE_VERSION'
          }
        }
      }
    }
  }
}