pipeline {
  agent {
    kubernetes {
      label 'default maven build-pod'
      defaultContainer 'docker'
      yamlFile 'build-pod.yaml'
    }
  }

  environment {
    DOCKER_HUB=credentials('dockerhub-cred')
    IMAGE_NAME='opeomotayo/java-image'
    IMAGE_VERSION='latest'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }

  stages {
    stage('Delete image if exists') {
      steps {
        dir('container-image-security/trivy-scan-image'){
          sh 'docker rmi $IMAGE_NAME:$IMAGE_VERSION || (echo "Image $IMAGE_NAME:$IMAGE_VERSION didnt exist so not removed."; exit 0)'
        }
      }
    }
    stage('Create container image') {
      steps {
        dir('container-image-security/trivy-scan-image'){
          sh 'docker build --tag $IMAGE_NAME:$IMAGE_VERSION .'
          sh 'docker image ls'
        }
      }
    }
    // stage('Publish Container Image') {
    //   steps {
    //     sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
    //     sh 'docker push $IMAGE_NAME:$IMAGE_VERSION'
    //   }
    // }
    stage('Scan For Image Vulnerabilities') {
      steps {
        dir('container-image-security/trivy-scan-image'){
          container('security-tools'){
            sh 'echo "$DOCKER_HUB_PSW" | docker login -u $DOCKER_HUB_USR --password-stdin'
            // sh 'trivy image --format spdx $IMAGE_NAME:$IMAGE_VERSION' // cyclonedx, json
            sh 'trivy image --no-progress --exit-code 0 --security-checks vuln --skip-update --severity MEDIUM,HIGH,CRITICAL $IMAGE_NAME:$IMAGE_VERSION'
          }
        }
      }
    }
  }
}